<?php ############# ORDER #################
	$bshowPos = Mage::getStoreConfigFlag('auit_pdf/auit_offer/table_show_pos');
	$baddSku = Mage::getStoreConfigFlag('auit_pdf/auit_offer/table_add_sku');
	$bshowQtyAsNumber = Mage::getStoreConfigFlag('auit_pdf/auit_offer/table_show_qty_number');
	$bshowSku=0;
	$bshowSku = Mage::getStoreConfigFlag('auit_pdf/invoice/table_show_sku');
	$cols=8;
	if ( !$bshowPos )
		$cols--;
	if (@!$bshowSku )
		$cols--;
?>
<?php $_order = $this->getOrder() ?>

<?php if ( $text = $this->getBuilBeforeTableText()) :?>
	<div class="text-before"><?php echo $text; ?></div>
<?php endif;?>
    <table class="data-table offer" border="0" cellpadding="2" cellspacing="0" >
    	<thead>
            <tr class="head">
            	<?php if ( $bshowPos ) :?>
            	<th class="col-position " ><?php echo $this->__('Pos.') ?></th>
            	<?php endif;?>
				<?php if (@$bshowSku ) :?>
                <th class="col-sku"><?php echo $this->__('SKU') ?></th>
                <?php endif;?>
                <th class="col-name" ><?php echo $this->__('Product Name') ?></th>
                <th class="col-qty"><?php echo $this->__('Qty') ?></th>
                <th class="col-price"><?php echo $this->__('Price') ?> / Unité<br /><span style="font-weight: normal; font-size: 0.9em">(net)</span>
				</th>
                <th class="col-mwst1"><?php echo $this->__('% de TVA') ?></th>
                <th class="col-mwst2"><?php echo $this->__('TVA') ?><br /></th>
                <th class="col-subtotal"><?php echo $this->__('Subtotal') ?><br /><span style="font-weight: normal; font-size: 0.9em">(brut)</span></th>
            </tr>
		</thead>
        <?php $_items = $_order->getItemsCollection(); ?>
        <?php $_count = 0; $rowNr=0;
	        foreach ($_items as $_item)
	        {
	        	 if ($_item->getParentItem() ) continue;
	        	$_count++;
	        }
			
	
                     
             
			 
        	$mediaHelper = Mage::helper('catalog/image');
        	?>
        <?php foreach ($_items as $_item): ?>
        <?php  if ($_item->getParentItem()) continue; ?>
            <?php 
            	$rowNr++;
            	$trClass = (($rowNr % 2) == 1)?'odd':'even';
            	if ( $rowNr == $_count )
            		$trClass .= ' lastx'; 
            	$row = $this->getItemHtml($_item);
            	$countTr = preg_match_all("|<tr[^>]*>(.*)</tr[^>]*>|usiU",$row,$resultTR, PREG_PATTERN_ORDER);
			?>
			<?php if ( $countTr > 0 ) foreach ( $resultTR[0] as $trIdx => $tr ) : ?>
				<?php
	            	$orderItemId = 0;
	            	if ( preg_match_all("|<tr[^i]*id=\"order-item-row-([0-9]*)\"[^>]*>|usiU",$tr,$result, PREG_PATTERN_ORDER) )
	            		$orderItemId = $result[1][0];
	            	$count = preg_match_all("|<td[^>]*>(.*)</td[^>]*>|usiU",$tr,$result, PREG_PATTERN_ORDER);
	            	if ( $count )
	            	{
		            	foreach ( $result[1] as &$td)
	            			$td = trim(str_replace(array("\n",'  ','display:none'),'',$td));
	            	}
	            	$_product = Mage::getModel('catalog/product')->load($_item->getData('product_id'));
	            	$imgPath='';
	            	if ( $_product->getId() )
	            	{
	            		$imgPath = ''.$mediaHelper->init($_product, 'small_image')->resize(135);
	            		$imgPath = str_replace(Mage::getBaseUrl('media'), Mage::getBaseDir('media').'/', $imgPath);
	            		$imgPath = str_replace('/', DS, $imgPath);
	            	}
	            ?>
				

				
	            <?php if ( $count && count($result[1]) >= 5 ) : ?>
	            <tr class="<?php  echo $trClass; ?>" nobr="true">
	           	<?php if ( $bshowPos ) :?>
	            	<td class="col-position " ><?php if ( $trIdx == 0 ) echo $rowNr; ?></td>
	           	<?php endif;?>
				<?php if (@$bshowSku ) :?>
	                <td class="col-sku"><span class="sku"><?php echo ($result[1][1]) ?></span></td>
	            <?php endif;?>
	                <td class="col-name" ><?php echo strip_tags($result[1][0]) ?>
	                <?php echo Mage::helper('auit_pdf')->showSKULine($baddSku,$result[1][1]);?>
	                </td>
	                <td class="col-qty"><?php echo ($result[1][3]) ?></td>
					
	                <td class="col-price"><?php echo number_format ($_item->getPrice(), 2, ',', ' '); ?> €</td>
					<td class="col-mwst1"><?php echo sprintf('%s%%', 0 + $_item->getTaxPercent()); ?></td>
	                <td class="col-mwst2"><?php echo number_format ($_item->getTaxAmount(), 2, ',', ' '); ?> €</td>

	                <td class="col-subtotal"><?php echo ($result[1][4]) ?></td>
	            </tr>
	            <?php else : ?>
	            	<?php echo $row; ?>
	            <?php endif;?>
            <?php endforeach; ?>
        <?php endforeach; ?>
		<tr class="last">
			<td colspan="<?php echo $cols?>"></td>

		</tr>
		<?php
			$row = $this->getChildHtml('order_totals');
			$row = str_replace('colspan="4"','colspan="'.($cols-1).'"',$row);
			$row = trim(str_replace(array("\n",'  ','display:none'),'',$row));
			$row = preg_replace('|(onclick="[^"]*")|','',$row);
			$row = preg_replace('|(&[^a])|','&amp; ',$row);
			$row = str_replace('<br /></td>','</td>',$row);
		?>
		<?php echo $row; ?>
</table>
<?php if ( $text = $this->getBuildAfterTableText()) :?>
	<br />
	<div class="text-after"><?php echo $text; ?></div>
<?php endif;?>

