
<?php
  $enablefacebook = $this->helper('sociallogin')->getEnableFacebook();
  $enabletwitter = $this->helper('sociallogin')->getEnableTwitter();
  $enablegoogle = $this->helper('sociallogin')->getEnableGoogle();
	$enablelinkedin = $this->helper('sociallogin')->getEnableLinkedin();
?>
<div class="col2-set">
  <?php echo $this->getChildHtml('login_before')?>
  <div class="col-1">
    <h3><?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?><?php echo $this->__('Checkout as a Guest or Register') ?><?php else: ?><?php echo $this->__('Register to Create an Account') ?><?php endif; ?></h3>
    <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
      <p><?php echo $this->__('Register with us for future convenience:') ?></p>
      <?php else: ?>
      <p><strong><?php echo $this->__('Register and save time!') ?></strong><br />
      <?php echo $this->__('Register with us for future convenience:') ?></p>
      <ul>
        <li><?php echo $this->__('Fast and easy check out') ?></li>
        <li><?php echo $this->__('Easy access to your order history and status') ?></li>
      </ul>
      <?php endif; ?>
    <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
      <ul class="form-list">
        <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
          <li class="control">
            <input type="radio" name="checkout_method" id="login:guest" value="guest"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Checkout_Model_Type_Onepage::METHOD_GUEST): ?> checked="checked"<?php endif; ?> class="radio" /><label for="login:guest"><?php echo $this->__('Checkout as Guest') ?></label>
          </li>
          <?php endif; ?>
        <li class="control">
          <input type="radio" name="checkout_method" id="login:register" value="register"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Checkout_Model_Type_Onepage::METHOD_REGISTER || !$this->getQuote()->isAllowedGuestCheckout()): ?> checked="checked"<?php endif ?> class="radio" /><label for="login:register"><?php echo $this->__('Register') ?></label>
        </li>
      </ul>
      <h4><?php echo $this->__('Register and save time!') ?></h4>
      <p><?php echo $this->__('Register with us for future convenience:') ?></p>
      <ul class="ul">
        <li><?php echo $this->__('Fast and easy check out') ?></li>
        <li><?php echo $this->__('Easy access to your order history and status') ?></li>
      </ul>
      <?php else: ?>
      <input type="hidden" name="checkout_method" id="login:register" value="register" checked="checked" />
      <?php endif; ?>
  </div>
  <div class="col-2">
    <h3><?php echo $this->__('Login') ?></h3>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form id="login-form" action="<?php echo $this->getPostAction() ?>" method="post">
      <fieldset>
        <h4><?php echo $this->__('Already registered?') ?></h4>
        <p><?php echo $this->__('Please log in below:') ?></p>
        <ul class="form-list">
          <li>
            <label for="login-email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
            <div class="input-box">
              <input type="text" class="input-text required-entry validate-email" id="login-email" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" />
            </div>
          </li>
          <li>
            <label for="login-password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
            <div class="input-box">
              <input type="password" class="input-text required-entry" id="login-password" name="login[password]" />
            </div>
          </li>
        </ul>
      </fieldset>
    </form>
  </div>
</div>
<div class="col2-set">
  <div class="col-1">
    <div class="buttons-set">
      <p class="required">&nbsp;</p>
      <button type="button" class="button" onclick="checkout.setMethod();"><span><span><?php echo ($this->getQuote()->isAllowedGuestCheckout() ? $this->__('Continue') : $this->__('Register')) ?></span></span></button>
    </div>
  </div>
  <div class="col-2">
    <div class="buttons-set">
      <p class="required"><?php echo $this->__('* Required Fields') ?></p>
      <a href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>" class="f-left"><?php echo $this->__('Forgot your password?') ?></a>
      <button type="submit" class="button" onclick="onepageLogin(this)"><span><span><?php echo $this->__('Login') ?></span></span></button>
      <a href="#loginwith" class="showform" class="fb_button_ps"><img src="<?php echo $this->helper('sociallogin')
		      ->getLoginWithImg()?>" alt="<?php echo $this->__('Login with')?>" /></a>

    </div>
  </div>
</div>

<!--end check out , Begin sociallogin -->

<div style="display: none;">
  <div style="display: none;">
    <div style="display: none;" class="allcontent" id="allcontent">
      <div class="message-all" id="message-all" style="font-size: 13px; color: red; height: 50px; margin-top: 30px;"><button type="button" onclick="return backlogin();" style="float: right; margin-top: 6px; margin-right: 6px;" class="button" title="<?php echo $this->__('Back') ?>"><span><span><?php echo $this->__('Back') ?></span></span></button></div>
<!--      <div id="divtwitter" style=" width: 300px; height: 150px;"> -->
      <div id="divtwitter"> 
        <div id="cboxLoadingGraphic" style="float: left; display: none;"></div>
        <div class="page-title">
          <h3><?php echo $this->__('Please enter your Twitter email'); ?></h3>
        </div>  
        <div id="twitter_error" style="color: red;"></div>
        <div class="socialpopup-input-box" style="margin-left: 25px;">
	        <input type="text" id="tw_email" name="tw_email" value="" class="input-text required-entry validate-email"/>

          <button type="button" onclick="return twitter_check();" style="float: right;" class="button"  title="<?php
	          echo $this->__('Login') ?>" name="twittermail" id="twittermail"><span><span><?php echo $this->__('Login') ?></span></span></button>
<!--          <button type="button" onclick="return backlogin();" style="float: right; margin-left: 10px; margin-right:-->
<!--          6px;"-->
<!--                  class="button" title="--><?php //echo $this->__('Back') ?><!--"><span><span>--><?php //echo $this->__('Back') ?><!--</span></span></button>-->
        </div>
        <div id="twitter_error"></div>
      </div>

	    <!-- facebook -->
	    <div id="divfacebook">
		    <div id="cboxLoadingGraphic" style="float: left; display: none;"></div>
		    <div class="page-title">
			    <h3><?php echo $this->__('Please enter your Facebook email'); ?></h3>
		    </div>
		    <div id="facebook_error" style="color: red;"></div>
		    <div class="socialpopup-input-box" style="margin-left: 25px;">
			    <input type="text" id="fb_email" name="fb_email" value="" class="input-text required-entry validate-email"/>

			    <button type="button" onclick="return fb_check();" style="float: right;" class="button"  title="<?php
				    echo $this->__('Login') ?>" name="facebookmail" id="facebookmail"><span><span><?php echo $this->__
							    ('Login')
						    ?></span></span></button>
<!--			    <button type="button" onclick="return backlogin();" style="float: right; margin-left: 10px; margin-right:-->
<!--          6px;"-->
<!--			            class="button" title="--><?php //echo $this->__('Back') ?><!--"><span><span>--><?php //echo $this->__('Back') ?><!--</span></span></button>-->
		    </div>
		    <div id="facebook_error"></div>
	    </div>

	    <!--google -->

	    <div id="divgoogle">
		    <div id="cboxLoadingGraphic" style="float: left; display: none;"></div>
		    <div class="page-title">
			    <h3><?php echo $this->__('Please enter your Google email'); ?></h3>
		    </div>
		    <div id="google_error" style="color: red;"></div>
		    <div class="socialpopup-input-box" style="margin-left: 25px;">
			    <input type="text" id="gg_email" name="gg_email" value="" class="input-text required-entry validate-email"/>

			    <button type="button" onclick="return google_check();" style="float: right;" class="button"  title="<?php
				    echo $this->__('Login') ?>" name="googlemail" id="googlemail"><span><span><?php echo $this->__
							    ('Login')
						    ?></span></span></button>
<!--			    <button type="button" onclick="return backlogin();" style="float: right; margin-left: 10px; margin-right:-->
<!--          6px;"-->
<!--			            class="button" title="--><?php //echo $this->__('Back') ?><!--"><span><span>--><?php //echo $this->__('Back') ?><!--</span></span></button>-->
		    </div>
		    <div id="google_error"></div>
	    </div>

    </div>
  </div>


  <div class="customer-login-with-social" id="loginwith">   
    <div class="page-title">
      <h1><?php echo $this->__('Sign in With') ?></h1>
    </div>

    <div class="content">    
      <ul>
        <?php if($enablefacebook):?>
          <li>
            <a href="#allcontent" onclick="facebooklogin()" class="facebook" id="facebook"><img src="<?php
		            echo
	            $this->helper('sociallogin')->getLoginImg()?>" alt="<?php echo $this->__('Connect with Facebook')?>" /></a>
          </li>
          <?php endif?>
        <?php if($enabletwitter):?>
          <li>
            <a href="#allcontent" onclick="return checktwitter();" class="twitter"><img src="<?php echo
	            $this->helper('sociallogin')->getTwitterImg()?>" alt="<?php echo $this->__('Connect with Twitter')?>" /></a>
          </li>
          <?php endif?>
        <?php if($enablegoogle):?>
          <li>
            <a href="#allcontent" onclick="return logingg();"  class="google"><img src="<?php echo $this->helper
		            ('sociallogin')->getGoogleImg()?>" alt="<?php echo $this->__('Connect with Google')?>" />
            </a>
          </li>
          <?php endif?>
	      <?php if($enablelinkedin): ?>
		      <li>
			      <a href="<?php  $block = $this->getLayout()->getBLockSingleton('sociallogin/sociallogin')->_getButtonUrl();
				      echo $this-> escapeUrl($block);?>" class="linkedin"><img src="<?php echo
				      $this->helper('sociallogin')->getLinkedinImg()?>" alt="<?php echo $this->__('Connect with Linkedin')?>" />
			      </a>
		      </li>
	      <?php endif ?>
      </ul>
    </div>  
  </div>    
</div>

<!-- end sociallogin -->

<script type="text/javascript">
  //<![CDATA[
  var loginForm = new VarienForm('login-form', true);
  $('login-email').observe('keypress', bindLoginPost);
  $('login-password').observe('keypress', bindLoginPost);
  function bindLoginPost(evt){
    if (evt.keyCode == Event.KEY_RETURN) {
      loginForm.submit();
    }
  }
  function onepageLogin(button)
  {
    if(loginForm.validator && loginForm.validator.validate()){
      button.disabled = true;
      loginForm.submit();
    }
  }
  jQuery(document).ready(function() {
    jQuery(".showform").fancybox({inline:true});
  });
  function backlogin(){
    document.getElementById('allcontent').style.display = "none";
    jQuery.fancybox.close();
  }
  //]]>
</script>