<?php
/**
 * This file is part of the official Amazon Pay and Login with Amazon extension
 * for Magento 1.x
 *
 * (c) 2017 creativestyle GmbH. All Rights reserved
 *
 * Distribution of the derivatives reusing, transforming or being built upon
 * this software, is not allowed without explicit written permission granted
 * by creativestyle GmbH
 *
 * @category   Creativestyle
 * @package    Creativestyle_AmazonPayments
 * @copyright  2017 creativestyle GmbH
 * @author     Marek Zabrowarny <ticket@creativestyle.de>
 */
?>
<?php /** @var Creativestyle_AmazonPayments_Block_Pay_Button $this */ ?>
<p>
<?php if ($this->getEnableOr()) : ?>
    <span class="amazonpayments-or"><?php echo $this->__('-OR-'); ?></span>
<?php endif; ?>
    <a id="<?php echo $this->getContainerId(); ?>" class="<?php echo $this->getContainerClass(); ?>"
<?php foreach ($this->getDataAttributes() as $attributeKey => $attributeValue) : ?>
        data-<?php echo $attributeKey; ?>="<?php echo $attributeValue; ?>"
<?php endforeach; ?>
    >
    </a>
</p>
