<?php   
/*
 * @copyright   Copyright ( c ) 2014 www.magebuzz.com
 */
	require (Mage::getBaseDir('lib') . '/Magebuzz/Twitter/twitteroauth.php');
?>
<script src="<?php echo $this->getJsUrl('magebuzz/sociallogin/jquery/1.7.1/jquery.min.js');?>" type="text/javascript"></script>
<script src="<?php echo $this->getJsUrl('magebuzz/sociallogin/jquery.fancybox.js');?>" type="text/javascript"></script>
<script language="JavaScript" type="text/javascript">
window.fbAsyncInit = function() {
	FB.init({appId: '<?php echo $this->getAppId()?>',
		status     : true,
		cookie     : true,
		xfbml      : true,
		oauth      : true});
};
(function(d){
	var js, id = 'facebook-jssdk'; if (d.getElementById(id)) {return;}
	js = d.createElement('script'); js.id = id; js.async = true;
	js.src = "//connect.facebook.net/<?php echo Mage::app()->getLocale()->getLocaleCode()?>/all.js";
	d.getElementsByTagName('head')[0].appendChild(js);
}(document));

function facebook_check(){
	jQuery.fancybox.showLoading();
	var email_value = document.getElementById("fb_email").value;
	var reg = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;
	if(email_value == '')
	{
		jQuery.fancybox.hideLoading();
		document.getElementById('facebook_error').innerHTML="<?php echo $this->__('This field is required'); ?>";
	} else if(reg.test(email_value) == false){
		jQuery.fancybox.hideLoading();
		document.getElementById('facebook_error').innerHTML="<?php echo $this->__('Invalid Email Address'); ?>";
		return false
	} else {
		document.getElementById('facebook_error').innerHTML="";
		var ajaxurl = "<?php echo Mage::getBaseUrl() . 'sociallogin/index/facebookcheck/?email_value='?>"+email_value;
		var  screenX    = typeof window.screenX != 'undefined' ? window.screenX : window.screenLeft;
		var   screenY    = typeof window.screenY != 'undefined' ? window.screenY : window.screenTop;
		var   outerWidth = typeof window.outerWidth != 'undefined' ? window.outerWidth : document.body.clientWidth;
		var   outerHeight = typeof window.outerHeight != 'undefined' ? window.outerHeight : (document.body.clientHeight - 22);
		var   width    = 790;
		var   height   = 350;
		var   left     = parseInt(screenX + ((outerWidth - width) / 2), 10);
		var   top      = parseInt(screenY + ((outerHeight - height) / 2.5), 10);
		var   features = (
			'width=' + width +
				',height=' + height +
				',left=' + left +
				',top=' + top
			);

		new Ajax.Request(ajaxurl, {
			method: 'post',
			parameters: {email_value: email_value},
			onSuccess: function(facebook_success_give) {
				var pattern_url = /(ftp|http|https):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/;
				var url_value=pattern_url.test(facebook_success_give.responseText);
				if(url_value ==false)
				{
					jQuery.fancybox.hideLoading();
					document.getElementById('facebook_error').innerHTML=facebook_success_give.responseText;
					return false;
				}else {
					jQuery.fancybox.hideLoading();
					document.getElementById('containerFb').style.display = 'none';
					jQuery.fancybox.close();
					FB.login(function(response) {
						if (response.status == 'connected') {
							login();

						}else if(response.status == 'unknown')
						{
							window.location.reload();
						}
						else{
							// user is not logged in

							document.getElementById('form-login').style.display = "block";
							document.getElementById('form-register').style.display = "none";
							document.getElementById('containerDiv').style.display = "none";
							document.getElementById('message-all').style.display = "block";
							if(response.status == 'not_authorized'){
								document.getElementById('message-all').innerHTML= 'Your Facebook account is not authorized for you to log in the system. ';
							}else{
								document.getElementById('message-all').innerHTML= 'Facebook log in is not configured correctly. Please contact the store owner. ';
							}
						}
					}, {scope:'email,publish_stream'});

					return false;
				}
			}
		});
	}
}

function logout(){
	document.location.href="<?php echo $this->getUrl('sociallogin/index/logout')?>";
}


 function login()
 {
	 document.location.href="<?php echo $this->getUrl('sociallogin/index/loginfacebook')?>?referer=<?php echo Mage::helper('core')->urlEncode($this->helper('core/url')->getCurrentUrl())?>";
 }

function loginFormAcion()
{
	jQuery.fancybox.showLoading();
	var xmlhttp;
	var username = document.getElementById("emaillogin").value;
	var password = document.getElementById("passlogin").value;
	var urlpost = '<?php echo Mage::getUrl('sociallogin/index/loginpost')?>';
	if (window.XMLHttpRequest)
	{// code for IE7+, Firefox, Chrome, Opera, Safari
		xmlhttp=new XMLHttpRequest();
	}
	else
	{// code for IE6, IE5
		xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
	}
	xmlhttp.onreadystatechange=function()
	{
		if (xmlhttp.readyState==4 && xmlhttp.status==200)
		{
			var responce = xmlhttp.responseText;
			var pattern_url = /(ftp|http|https):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/;
			var url_value=pattern_url.test(responce);
			//responce = responce.trim();
			if(url_value)
			{
				window.location = responce;
				jQuery.fancybox.hideLoading();
				//jQuery.fancybox.close();
				document.getElementById('login_error').innerHTML = '';
			}
			else{
				jQuery.fancybox.hideLoading();
				document.getElementById('login_error').innerHTML = responce;
			}
		}
	}

	xmlhttp.open("GET",urlpost+'?username='+username+'&password='+password,true);
	xmlhttp.send();
}

function forgotFormAction(){
	jQuery.fancybox.showLoading();
	var email_value = document.getElementById("email-forgot").value;
	var ajaxurl = "<?php echo Mage::getBaseUrl() . 'sociallogin/index/forgotpassword'?>";
	new Ajax.Request(ajaxurl, {
		method: 'post',
		parameters: {email: email_value},
		onSuccess: function(forgot_success_give) {
			if(forgot_success_give.responseText =='okforgot')
			{
				jQuery.fancybox.hideLoading();
				document.getElementById('content').style.display = "none";
				document.getElementById('message-forgot').innerHTML= 'If there is an account associated with '+email_value+' you will receive an email with a link to reset your password.';
			}else{
				jQuery.fancybox.hideLoading();
				document.getElementById('forgot-error').innerHTML= forgot_success_give.responseText;
			}
		}
	});
}

	function logingg()
	{
		var  screenX    = typeof window.screenX != 'undefined' ? window.screenX : window.screenLeft;
		var   screenY    = typeof window.screenY != 'undefined' ? window.screenY : window.screenTop;
		var   outerWidth = typeof window.outerWidth != 'undefined' ? window.outerWidth : document.body.clientWidth;
		var   outerHeight = typeof window.outerHeight != 'undefined' ? window.outerHeight : (document.body.clientHeight - 22);
		var   width    = 420;
		var   height   = 500;
		var   left     = parseInt(screenX + ((outerWidth - width) / 2), 10);
		var   top      = parseInt(screenY + ((outerHeight - height) / 2.5), 10);
		var   features = (
			'width=' + width +
				',height=' + height +
				',left=' + left +
				',top=' + top
			);
		jQuery.fancybox.close();
		var ajaxurl = "<?php echo Mage::getUrl('sociallogin/index/googlelogin',array('referer'=>Mage::helper('core')->urlEncode(Mage::helper('core/url')->getCurrentUrl())));?>";
		newwindow=window.open(ajaxurl,'Login_by_google',features);
	}

	function loginlinkedin()
	{
		
	}


  function twitter_check() {
    jQuery.fancybox.showLoading();      
    var email_value = document.getElementById("tw_email").value;
    var reg = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;
    if(email_value=='')
      {
      jQuery.fancybox.hideLoading();
      document.getElementById('twitter_error').innerHTML="<?php echo $this->__('This field is required'); ?>";      
    } else if(reg.test(email_value) == false) {
      jQuery.fancybox.hideLoading();
      document.getElementById('twitter_error').innerHTML="<?php echo $this->__('Invalid Email Address'); ?>";
      return false;
    }else{
      document.getElementById('twitter_error').innerHTML="";
      var ajaxurl = "<?php echo Mage::getBaseUrl() . 'sociallogin/index/twitterpost/?email_value='?>"+email_value;
      var  screenX    = typeof window.screenX != 'undefined' ? window.screenX : window.screenLeft;
      var   screenY    = typeof window.screenY != 'undefined' ? window.screenY : window.screenTop;
      var   outerWidth = typeof window.outerWidth != 'undefined' ? window.outerWidth : document.body.clientWidth;
      var   outerHeight = typeof window.outerHeight != 'undefined' ? window.outerHeight : (document.body.clientHeight - 22);
      var   width    = 790;
      var   height   = 350;
      var   left     = parseInt(screenX + ((outerWidth - width) / 2), 10);
      var   top      = parseInt(screenY + ((outerHeight - height) / 2.5), 10);
      var   features = (
      'width=' + width +
      ',height=' + height +
      ',left=' + left +
      ',top=' + top
      );

      new Ajax.Request(ajaxurl, {
        method: 'post',
        parameters: {email_value: email_value},
        onSuccess: function(twitter_success_give) {
          var pattern_url = /(ftp|http|https):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/;
          var url_value=pattern_url.test(twitter_success_give.responseText);
          if(url_value == false)
            {
            jQuery.fancybox.hideLoading();
            document.getElementById('twitter_error').innerHTML=twitter_success_give.responseText;
            return false;
          }else
            {
            jQuery.fancybox.hideLoading();
            jQuery.fancybox.close();    
            newwindow=window.open(twitter_success_give.responseText,'Login_by_twitter',features);

            if (window.focus) {
              newwindow.focus()
            }
            return false;
          }
        }
      });
    }
  }
  var newwindow;


  function registerAction()
  {
    jQuery.fancybox.showLoading();
    var dataform = jQuery('form#register-form').serialize();
    document.getElementById('register_error').innerHTML="";
    var ajaxurl = "<?php echo Mage::getBaseUrl() . 'sociallogin/index/registeraccount?'?>"+dataform;
    new Ajax.Request(ajaxurl,{
      method:'Get',
      onSuccess: function(register_success_give) {
        var pattern_url = /(ftp|http|https):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/;
        var url_value=pattern_url.test(register_success_give.responseText);
        if(url_value ==false)
          {
          jQuery.fancybox.hideLoading();
          document.getElementById('register_error').innerHTML=register_success_give.responseText;
          return false;
        }else
          {
          jQuery.fancybox.hideLoading();
          jQuery.fancybox.close();
          window.location.href=register_success_give.responseText;
        }
      }
    });

  }

	function loginLinkedin()
	{
		var  screenX    = typeof window.screenX != 'undefined' ? window.screenX : window.screenLeft;
		var   screenY    = typeof window.screenY != 'undefined' ? window.screenY : window.screenTop;
		var   outerWidth = typeof window.outerWidth != 'undefined' ? window.outerWidth : document.body.clientWidth;
		var   outerHeight = typeof window.outerHeight != 'undefined' ? window.outerHeight : (document.body.clientHeight - 22);
		var   width    = 420;
		var   height   = 500;
		var   left     = parseInt(screenX + ((outerWidth - width) / 2), 10);
		var   top      = parseInt(screenY + ((outerHeight - height) / 2.5), 10);
		var   features = (
			'width=' + width +
				',height=' + height +
				',left=' + left +
				',top=' + top
			);
		jQuery.fancybox.close();
		jQuery.fancybox.hideLoading();
<!--		var ajaxurl = "--><?php //_getButtonUrl()?><!--";-->
<!--		newwindow=window.open(ajaxurl,'Login_by_google',features);-->
	}

  ///customer page and checkout page

function fb_check(){
	jQuery.fancybox.showLoading();
	var email_value = document.getElementById("fb_email").value;
	var reg = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;
	if(email_value == '')
	{
		jQuery.fancybox.hideLoading();
		document.getElementById('facebook_error').innerHTML="<?php echo $this->__('This field is required'); ?>";
	} else if(reg.test(email_value) == false){
		jQuery.fancybox.hideLoading();
		document.getElementById('facebook_error').innerHTML="<?php echo $this->__('Invalid Email Address'); ?>";
		return false
	} else {
		document.getElementById('facebook_error').innerHTML="";
		var ajaxurl = "<?php echo Mage::getBaseUrl() . 'sociallogin/index/facebookcheck/?email_value='?>"+email_value;
		var  screenX    = typeof window.screenX != 'undefined' ? window.screenX : window.screenLeft;
		var   screenY    = typeof window.screenY != 'undefined' ? window.screenY : window.screenTop;
		var   outerWidth = typeof window.outerWidth != 'undefined' ? window.outerWidth : document.body.clientWidth;
		var   outerHeight = typeof window.outerHeight != 'undefined' ? window.outerHeight : (document.body.clientHeight - 22);
		var   width    = 790;
		var   height   = 350;
		var   left     = parseInt(screenX + ((outerWidth - width) / 2), 10);
		var   top      = parseInt(screenY + ((outerHeight - height) / 2.5), 10);
		var   features = (
			'width=' + width +
				',height=' + height +
				',left=' + left +
				',top=' + top
			);

		new Ajax.Request(ajaxurl, {
			method: 'post',
			parameters: {email_value: email_value},
			onSuccess: function(facebook_success_give) {
				var pattern_url = /(ftp|http|https):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/;
				var url_value=pattern_url.test(facebook_success_give.responseText);
				if(url_value ==false)
				{
					jQuery.fancybox.hideLoading();
					document.getElementById('facebook_error').innerHTML=facebook_success_give.responseText;
					return false;
				}else {
					jQuery.fancybox.hideLoading();
					document.getElementById('divfacebook').style.display = 'none';
					jQuery.fancybox.close();
					FB.login(function(response) {

						if (response.status == 'connected') {
							login();
						} else {
							// user is not logged in
							window.location.reload();
						}
					}, {scope:'email,publish_stream'});
					return false;
				}
			}
		});
	}
}

  function checktwitter() {
    var checktwitter = '<?php echo Mage::getSingleton('sociallogin/api_twitter')->checkConnectionTwitter();?>';
    if (checktwitter == '') {
      document.getElementById('divtwitter').style.display = "none";
      document.getElementById('allcontent').style.display = "block";
      document.getElementById('message-all').style.display = "block";
      document.getElementById('message-all').innerHTML= 'Twitter log in is not configured correctly. Please contact the store owner. ';
    } else {
      document.getElementById('divtwitter').style.display = "block";
      document.getElementById('allcontent').style.display = "block";
      document.getElementById('message-all').style.display = "none";
      document.getElementById('divfacebook').style.display = "none";
      document.getElementById('divgoogle').style.display = "none";
    }

    jQuery(document).ready(function() {
          jQuery(".twitter").fancybox({inline:true});
        });
  }

	function facebooklogin(){
		document.getElementById('divfacebook').style.display = "block";
		document.getElementById('allcontent').style.display = "block";
		document.getElementById('message-all').style.display = "none";
		document.getElementById('divtwitter').style.display = "none";
		document.getElementById('divgoogle').style.display = "none";

		jQuery(document).ready(function() {
			jQuery(".facebook").fancybox({inline:true});
		});
	}

function googleLogin(){
	document.getElementById('divgoogle').style.display = "block";
	document.getElementById('allcontent').style.display = "block";
	document.getElementById('message-all').style.display = "none";
	document.getElementById('divtwitter').style.display = "none";
	document.getElementById('divfacebook').style.display = "none"

	jQuery(document).ready(function() {
		jQuery(".google").fancybox({inline:true});
	});

}


  jQuery(document).ready(function() {
    jQuery(".sociallogin").fancybox();
  });

  /*]]>*/
      </script>