<?php
/**
 * Lucid Path Consulting SalesRep Extension
 *
 * LICENSE
 *
 *  1.  This is an agreement between Licensor and Licensee, who is being licensed to use the named Software.
 *  2.  Licensee acknowledges that this is only a limited nonexclusive license. Licensor is and remains the owner of all titles, rights, and interests in the Software.
 *  3.  This License permits Licensee to install the Software one (1) Magento web store per purchase. Licensee will not duplicate, reproduce, alter, or resell software.
 *  4.  This software is provided as-is with no warranty or guarantee whatsoever.
 *  5.  In the event of a defect or malfunction of the software, refunds or exchanges will be provided at the sole discretion of the licensor. Licensor reserves the right to refuse a refund, and maintains the policy that "all sales are final."
 *  6.  LICENSOR IS NOT LIABLE TO LICENSEE FOR ANY DAMAGES, INCLUDING COMPENSATORY, SPECIAL, INCIDENTAL, EXEMPLARY, PUNITIVE, OR CONSEQUENTIAL DAMAGES, CONNECTED WITH OR RESULTING FROM THIS LICENSE AGREEMENT OR LICENSEE'S USE OF THIS SOFTWARE.
 *  7.  Licensee agrees to defend and indemnify Licensor and hold Licensor harmless from all claims, losses, damages, complaints, or expenses connected with or resulting from Licensee's business operations.
 *  8.  Licensor has the right to terminate this License Agreement and Licensee's right to use this Software upon any material breach by Licensee.
 *  9.  Licensee agrees to return to Licensor or to destroy all copies of the Software upon termination of the License.
 *  10. This License Agreement is the entire and exclusive agreement between Licensor and Licensee regarding this Software. This License Agreement replaces and supersedes all prior negotiations, dealings, and agreements between Licensor and Licensee regarding this Software.
 *  11. This License Agreement is governed by the laws of California, applicable to California contracts.
 *  12. This License Agreement is valid without Licensor's signature. It becomes effective upon the download of the Software. *
 *
 * @category   LucidPath
 * @package    LucidPath_SalesRep_Deluxe
 * @author     Yuriy Malov
 * @copyright  Copyright (c) 2014 Lucid Path Consulting (http://www.lucidpathconsulting.com/)
 */
?>
<?php
$admins = Mage::helper('salesrep')->getAdminsList();
?>
<form id="co-salesrep-form" action="">
  <ul class="form-list">
    <li>
      <label for="salesrep_name" class="required"><em>*</em><?php echo Mage::getStoreConfig('salesrep/step_setup/step_label')?></label>
      <div class="input-box">
        <select id="salesrep_rep_id" name="salesrep_rep" class="validate-select">
          <option value=""></option>
          <?php foreach($admins as $admin): ?>
          <option value="<?php echo $admin['value'] ?>"><?php echo $admin['label'] ?></option>
          <?php endforeach; ?>
        </select>
      </div>
      <div style="display: none;" id="advice-validate-select-salesrep-name" class="validation-advice">
        <?php echo Mage::getStoreConfig('salesrep/step_setup/step_error_msg')?>
      </div>
    </li>
  </ul>
</form>

<div class="buttons-set" id="salesrep-buttons-container">
  <p class="required"><?php echo $this->__('* Required Fields') ?></p>
  <p class="back-link"><a href="#" onclick="checkout.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
  <button type="button" class="button" onclick="salesrep.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
  <span class="please-wait" id="salesrep-please-wait" style="display:none;">
    <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
  </span>
</div>

<script type="text/javascript">
//<![CDATA[
var Salesrep = Class.create();
Salesrep.prototype = {
  initialize: function(form, saveUrl){
    this.form = form;
    if ($(this.form)) {
      $(this.form).observe('submit', function(event){this.save();Event.stop(event);}.bind(this));
    }
    this.saveUrl = saveUrl;
    this.onSave = this.nextStep.bindAsEventListener(this);
    this.onComplete = this.resetLoadWaiting.bindAsEventListener(this);
  },

  save: function(){
    if (checkout.loadWaiting!=false) return;

    var validator = new Validation(this.form);
    if (validator.validate()) {

      checkout.setLoadWaiting('salesrep');

      var request = new Ajax.Request(
        this.saveUrl,
        {
          method: 'post',
          onComplete: this.onComplete,
          onSuccess: this.onSave,
          onFailure: checkout.ajaxFailure.bind(checkout),
          parameters: Form.serialize(this.form)
        }
      );
    }
  },

  onComplete: function(){
    alert('onComplete');
  },

  onSave: function(){
    alert('onSave');
  },

  resetLoadWaiting: function(transport){
    checkout.setLoadWaiting(false);
  },

  nextStep: function(transport){
    if (transport && transport.responseText){
      try {
        response = eval('(' + transport.responseText + ')');
      } catch (e) {
        response = {};
      }
    }

    if (response.error){
      if ((typeof response.message) == 'string') {
        alert(response.message);
      } else {
        if (window.billingRegionUpdater) {
          billingRegionUpdater.update();
        }

        alert(response.message.join("\n"));
      }

      return false;
    }

    checkout.setStepResponse(response);
  }
}

var salesrep = new Salesrep('co-salesrep-form', '<?php echo $this->getUrl('checkout/onepage/saveSalesrep') ?>');

Event.observe(window, "load", function(){
  checkout.steps.splice(checkout.steps.indexOf('review'), 0, 'salesrep');
});
//]]>
</script>