<div style="color:#777;font-size:10px;margin:0px 0px 15px 0px;overflow:hidden;width:500px">
  <p style="font-size:14px;color:#000"><strong><?php echo $this->__('Bitte nehmen Sie sich kurz Zeit diese Antwort zu bewerten....')?></strong></p>
  <div style="width:130px;float:left;margin-right:20px">
    <a href="<?php echo $this->getRateUrl(3) ?>" target="_blank"><img src="http://www.kopiererhaus.de/skin/frontend/default/kopiererhaus/images/smile/3.png" width="40" height="40" alt="<?php echo $this->__('Sehr gut')?>" border="0"></a>
    <h2 style="margin:0 0 5px 0">
      <a href="<?php echo $this->getRateUrl(3) ?>" style="color:#690" target="_blank"><?php echo $this->__('Ich bin zufrieden!')?></a>
    </h2><p style="line-height:normal;margin:0"><?php echo $this->__('Schnell, freundlich, hilfreich, zuvorkommend. Gute Arbeit!')?></p>
  </div>

  <div style="width:130px;float:left; margin-right:20px">
    <a href="<?php echo $this->getRateUrl(2) ?>" tar=
get="_blank">
      <img src="http://www.kopiererhaus.de/skin/frontend/default/kopiererhaus/images/smile/2.png" width="40" height="40" alt="<?php echo $this->__('OK')?>" border="0">
    </a>
    <h2 style="margin:0 0 5px 0">
   <a href="<?php echo $this->getRateUrl(2) ?>" target="_blank"><?php echo $this->__('Ich bin nicht zufrieden')?></a>
    </h2>
    <p style="line-height:normal;margin:0"><?php echo $this->__('Es war gut, aber es hätte besser sein können.')?></p>
  </div>

  <div style="width:130px;float:left;">
    <a href="<?php echo $this->getRateUrl(1) ?>" target="_blank"><img src="http://www.kopiererhaus.de/skin/frontend/default/kopiererhaus/images/smile/1.png" width="40" height="40" alt="<?php echo $this->__('Nicht gut')?>" border="0"></a>
    <h2 style="margin:0 0 5px 0"><a href="<?php echo $this->getRateUrl(1) ?>" style="color:#c00" target="_blank"><?php echo $this->__('Ich bin unzufrieden')?></a>
    </h2>
    <p style="line-height:normal;margin:0"><?php echo $this->__('Leider war ich überhaupt nicht zufrieden.')?></p>
  </div>
</div>